### ISSUE TITLE
Problem accessing templates directory

### ISSUE THREAD

**Issue by brucemontegani** [hummingbird-project/hummingbird-mustache#14]
The documentation does not state whether the directory for the the template directory can be relative.

``` swift
app.mustache = try .init(directory: "templates")
```

Is template relative to some other directory or is it the full path. Full path does not seem to make sense.

I have not been able to get my program to find the template directory.

**Comment by adam-fowler** [comment]
Hi @brucemontegani have you set the working folder in Xcode. Set it to the same folder as your project and you should be able to use relative paths from your project.

**Comment by brucemontegani** [comment]
I am not using Xcode. I am using VSCode.

**Comment by brucemontegani** [comment]
OK. I figured it out. I had to put it outside the "Sources" directory but inside the project directory.

```
<project-dir>
   Sources
        main.swift
   templates
        index.html
   Tests
```

**Comment by adam-fowler** [comment]
Closing as resolved
