### ISSUE TITLE
arrays of child objects

### ISSUE THREAD

**Issue by JaapWijnen** [hummingbird-project/hummingbird-mustache#15]
Not 100% sure if this is expected to work like this but the following approach currently doesn't work although it seems natural to me.

```
struct Context {
    let name: String
    let properties: [Property]
}
struct Property {
   let name: String
   let type: String
}
```

with the following template
```
struct {{name}} {
    {{#properties}}
    // properties
    var {{name}}: {{type}}
    {{/properties}}
}
```

Currently only renders: 
```
struct Thing {
    //properties
}
```

Maybe I shouldn't expect this to work? What would be the way to make this work?

**Comment by JaapWijnen** [comment]
100% my fault for referencing the wrong template, a similar copy 😅

**Comment by adam-fowler** [comment]
Yeah was just about to say it works for me.
